version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.9
 build: 
  commands:
   - sam build
   - export BUCKET=photostore2
   - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file template2.yaml
artifacts:
 type: zip
 files:
  - "**/*"